#
# Makefile for process structure
#

PS_OBJS		 =  process.o \
		   kill.o \
		   token.o \
		   suspend.o \
		   thread.o \
		   psmgr.o \
		   query.o \
		   cid.o \
		   flush.o

$(MODULE)-objs	+= $(addprefix ps/, $(PS_OBJS))
