#
# Makefile for msg management
#

MSG_OBJS	:=  queue.o \
				window.o \
				winstation.o \
				region.o \
				atom.o \
				hook.o \
				class.o \
				user.o

$(MODULE)-objs	+= $(addprefix msg/, $(MSG_OBJS))
