#
# Makefile for memory management
#

MM_OBJS		:= attach.o \
		   process.o \
		   section.o \
		   virtual.o \
		   datasection.o \
		   imagesection.o

$(MODULE)-objs	+= $(addprefix mm/, $(MM_OBJS))
