#
# Makefile for object management
#

OB_OBJS		+= wait.o \
		   dirobj.o \
		   display.o \
		   handle.o \
		   namespc.o \
		   object.o \
		   symlink.o \
		   ntobj.o

$(MODULE)-objs	+= $(addprefix ob/, $(OB_OBJS))
